### ISSUE TITLE
support extended extension listing

### ISSUE THREAD

**Issue by tkellen** [js-cli/js-liftoff#47]
/ref tkellen/js-interpret#25

**Comment by mjhm** [comment]
Note that this is the source of an [issue on knex.js](https://github.com/tgriesser/knex/issues/1137)

**Comment by phated** [comment]
This should already be supported, can you put together a reproduction repo?

**Comment by mjhm** [comment]
@phated Here you go: https://github.com/mjhm/hacker_test

**Comment by phated** [comment]
@mjhm thank you so much for the repo.  I was able to track down the problem rather quickly.  It seems that we added the support in 2.1 but the hacker module and knex both have liftoff pinned with `~` instead of `^` so they don't receive anything past `2.0.x`.  I'm going to close this and post the same findings on the knex issue.  Thanks again.
